const products = [
  {
    id: 1,
    slug: 'checked-top-with-asymmetric-neckline',
    name: "Checked Top with Asymmetric Neckline",
    imageUrl: "/img/product-test.jpg",
    images: [
      "/img/product-test.jpg",
      "/img/product-test.jpg",
      "/img/product-test.jpg",
      "/img/product-test.jpg",
    ],
    price: "EGP 2,990.00",
    originalPrice: "EGP 4,990.00",
    isNew: false,
    isSale: true,
    description: "Long top made in a flowing fabric. Asymmetric neckline. Check print.",
    color: "BLACK",
    reference: "REF. 5157/650",
    sizes: ['XS', 'S', 'M', 'L'],
    modelInfo: "The model wears size S and is 179 cm tall.",
    discountPercentage: 40,
  },
  {
    id: 2,
    slug: 'mid-rise-wide-leg-jeans',
    name: "Mid-Rise Wide-Leg Full Length Jeans",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,490.00",
    originalPrice: "EGP 4,150.00",
    isNew: false,
    isSale: true,
    discountPercentage: 40,
  },
  {
    id: 3,
    slug: 'rhinestone-leather-sandals',
    name: "Rhinestone Leather Sandals",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 1,990.00",
    originalPrice: "EGP 9,950.00",
    isNew: false,
    isSale: true,
    discountPercentage: 80,
  },
  {
    id: 4,
    slug: 'oval-hoop-earrings',
    name: "Oval Hoop Earrings",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 1,790.00",
    originalPrice: "EGP 3,980.00",
    isNew: false,
    isSale: true,
    discountPercentage: 55,
  },
  {
    id: 5,
    name: "Evening Gown",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 3,299.00",
    originalPrice: "EGP 3,999.00",
    isNew: false,
    isSale: true,
  },
  {
    id: 6,
    name: "Summer Maxi Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,199.00",
    originalPrice: "EGP 2,299.00",
    isNew: false,
    isSale: false,
  },
  {
    id: 7,
    name: "Cocktail Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,599.00",
    originalPrice: "EGP 2,299.00",
    isNew: true,
    isSale: false,
  },
  {
    id: 8,
    name: "Boho Midi Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 1,899.00",
    originalPrice: "EGP 2,299.00",
    isNew: false,
    isSale: true,
  },
  {
    id: 9,
    name: "Formal Evening Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,899.00",
    originalPrice: "EGP 2,299.00",
    isNew: false,
    isSale: false,
  },
  {
    id: 10,
    name: "Casual Day Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 1,399.00",
    originalPrice: "EGP 2,299.00",
    isNew: false,
    isSale: false,
  },
  {
    id: 11,
    name: "Elegant A-Line Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,499.00",
    originalPrice: "EGP 2,999.00",
    isNew: false,
    isSale: true,
  },
  {
    id: 12,
    name: "Beach Cover-Up Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 999.00",
    originalPrice: "EGP 2,299.00",
    isNew: true,
    isSale: false,
  },
  {
    id: 13,
    name: "Office Appropriate Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 1,799.00",
    originalPrice: "EGP 2,299.00",
    isNew: false,
    isSale: false,
  },
  {
    id: 14,
    name: "Party Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,199.00",
    originalPrice: "EGP 2,599.00",
    isNew: false,
    isSale: true,
  },
  {
    id: 15,
    name: "Wedding Guest Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,799.00",
    originalPrice: "EGP 2,299.00",
    isNew: true,
    isSale: false,
  },
  {
    id: 16,
    name: "Summer Sundress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 1,299.00",
    originalPrice: "EGP 2,299.00",
    isNew: false,
    isSale: false,
  },
  {
    id: 17,
    name: "Formal Business Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,399.00",
    originalPrice: "EGP 2,799.00",
    isNew: false,
    isSale: true,
  },
  {
    id: 18,
    name: "Casual Weekend Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 1,599.00",
    originalPrice: "EGP 2,299.00",
    isNew: false,
    isSale: false,
  },
  {
    id: 19,
    name: "Elegant Evening Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 3,199.00",
    originalPrice: "EGP 2,299.00",
    isNew: true,
    isSale: false,
  },
  {
    id: 20,
    name: "Summer Boho Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 1,899.00",
    originalPrice: "EGP 2,199.00",
    isNew: false,
    isSale: true,
  },
  {
    id: 21,
    name: "Cocktail Party Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,299.00",
    originalPrice: "EGP 2,299.00",
    isNew: false,
    isSale: false,
  },
  {
    id: 22,
    name: "Formal Occasion Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,899.00",
    originalPrice: "EGP 3,299.00",
    isNew: false,
    isSale: true,
  },
  {
    id: 23,
    name: "Casual Summer Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 1,399.00",
    originalPrice: "EGP 2,299.00",
    isNew: true,
    isSale: false,
  },
  {
    id: 24,
    name: "Elegant Midi Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,199.00",
    originalPrice: "EGP 2,299.00",
    isNew: false,
    isSale: false,
  },
  {
    id: 25,
    name: "Party Night Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,499.00",
    originalPrice: "EGP 2,899.00",
    isNew: false,
    isSale: true,
  },
  {
    id: 26,
    name: "Business Casual Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 1,799.00",
    originalPrice: "EGP 2,299.00",
    isNew: false,
    isSale: false,
  },
  {
    id: 27,
    name: "Summer Evening Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,599.00",
    originalPrice: "EGP 2,299.00",
    isNew: true,
    isSale: false,
  },
  {
    id: 28,
    name: "Formal Gala Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 3,599.00",
    originalPrice: "EGP 3,999.00",
    isNew: false,
    isSale: true,
  },
  {
    id: 29,
    name: "Casual Day Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 1,299.00",
    originalPrice: "EGP 2,299.00",
    isNew: false,
    isSale: false,
  },
  {
    id: 30,
    name: "Elegant Cocktail Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,399.00",
    originalPrice: "EGP 2,299.00",
    isNew: false,
    isSale: false,
  },
  {
    id: 31,
    name: "Summer Maxi Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,199.00",
    originalPrice: "EGP 2,599.00",
    isNew: false,
    isSale: true,
  },
  {
    id: 32,
    name: "Formal Business Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,799.00",
    originalPrice: "EGP 2,299.00",
    isNew: true,
    isSale: false,
  },
  {
    id: 33,
    name: "Casual Weekend Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 1,599.00",
    originalPrice: "EGP 2,299.00",
    isNew: false,
    isSale: false,
  },
  {
    id: 34,
    name: "Elegant Evening Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 3,299.00",
    originalPrice: "EGP 3,699.00",
    isNew: false,
    isSale: true,
  },
  {
    id: 35,
    name: "Summer Boho Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 1,899.00",
    originalPrice: "EGP 2,299.00",
    isNew: false,
    isSale: false,
  },
  {
    id: 36,
    name: "Cocktail Party Dress",
    imageUrl: "/img/product-test.jpg",
    price: "EGP 2,299.00",
    originalPrice: "EGP 2,299.00",
    isNew: true,
    isSale: false,
  },
];

export default products; 