import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar, { NavbarProvider } from "@/components/Navbar";
import NewsletterPopup from "@/components/NewsletterPopup";
import WhatsAppSupport from "@/components/WhatsAppSupport";
import RecaptchaProvider from "@/components/RecaptchaProvider";
import { CartProvider } from "@/contexts/CartContext";
import { UserProvider } from "@/contexts/UserContext";
import { WishlistProvider } from "@/contexts/WishlistContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RecaptchaProvider>
          <NavbarProvider>
            <UserProvider>
              <CartProvider>
                <WishlistProvider>
                  <Navbar />
                  {children}
                </WishlistProvider>
              </CartProvider>
            </UserProvider>
          </NavbarProvider>
        </RecaptchaProvider>
        <NewsletterPopup />
        <WhatsAppSupport />
      </body>
    </html>
  );
}